#include<bits/stdc++.h>
#include <ext/pb_ds/assoc_container.hpp> 
#include <ext/pb_ds/tree_policy.hpp>
using namespace std;
using namespace __gnu_pbds;
template<class T> using pbset=tree<T, null_type, less<T>, rb_tree_tag,tree_order_statistics_node_update> ;
template<class T> using pbmultiset=tree<T, null_type, less_equal<T>, rb_tree_tag,tree_order_statistics_node_update> ;
typedef long long ll;
typedef unsigned long long ull;
typedef long double ld;
#define f(i,a,b) for(long long i=a;i<=b;i++)
#define rf(i,a,b) for(long long i=a;i>=b;i--)
#define fastio() ios_base::sync_with_stdio(false);cin.tie(NULL);cout.tie(NULL)
#define P 1000000007
#define P1 998244353
#define llINT_MAX 9e18
#define iINT_MAX 1e9
#define endl "\n"
#define pb push_back
#define ppb pop_back
#define eb emplace_back
#define mkp make_pair
#define ff first
#define ss second
#define vii vector<int>
#define vll vector<ll>
#define vvl vector<vll>
#define p_q priority_queue
#define pqmax priority_queue<ll>
#define pqmin priority_queue<ll,vector<ll>,greater<ll>>
#define PI 3.141592653589793238462
#define set_bits __builtin_popcountll
#define sz(x) ((int)(x).size())
#define all(x) (x).begin(), (x).end()
#define YES cout << "YES" << "\n"
#define NO cout << "NO" << "\n"
#define yes cout << "Yes" << "\n"
#define no cout << "No" << "\n"
#define gg cout << -1 << "\n"
#define ln cout << "\n"
#define re return
template <class T> istream& operator >> (istream &is, vector<T> &v) { for(auto &i : v)    is >> i; return is; };
template <class T> ostream& operator << (ostream &os, vector<T> &v) { for(auto &i : v)    os << i << " "; cout << "\n"; return os; };
#ifndef ONLINE_JUDGE
#include <algo/debug.h>
#else
#define dbg(...) ;
#define debug(...) ;
#define crndl ;
#endif
long long POW(long long a,long long b){return (long long)(pow(a,b)+0.5);}
long long gcd(long long a,long long b){return __gcd(a,b);}
long long lcm(long long a,long long b){return (a*b)/__gcd(a,b);}
long long Ceil(long long a,long long b){return (a+b-1)/b;}
long long Sqrt(long long x){ long long y=sqrt(x)+5;while(y*y>x)y--;return y;}
long long sq(long long x){return (1ll*x*x);}
/*-------------------> Greedy / Constructive <----------------------
                        D T D P G B
⭐ D -> Decode the operation
⭐ T -> Think in reverse
⭐ D -> Dimensional Setup
⭐ P -> Prefix or Suffix ideas
⭐ G -> Greedy / Sorting
⭐ B -> Bit Manipulation
-----------------------------------------------------------------------------------------------------------------------------------------------------------------*/

// int n;
vector<bool> isPrime(105, 1);
vector<bool> have(50, 1); 

int rec(int lvl, int prev, int n) {
    // pruning case
    
    // base case 
    if(lvl == n) {
        if(isPrime[prev + 1])
            return 1;
        else return 0;
    }

    // recursive case
    ll cnt = 0;
    for(int i = 1 + (prev % 2); i <= n; i += 2) {          // pruning 3
        if(have[i] and isPrime[i + prev]) {
            have[i] = 0;
            cnt += rec(lvl + 1, i, n);
            have[i] = 1;
        }
    }

    return cnt;
}

void solve()
{
    cout << "{";
    f(n, 1, 17) {
        if(n & 1) {               // pruning 1 
            cout << 0 << ", ";
            continue;
        }

        have.assign(50, 1);
        have[1] = 0;
        cout << rec(1, 1, n) << ", ";        // rec(lvl, prev)     // pruning 2----- by taking prev = 1 initially
    }
    cout << "}";
}

///////////////////////////////////////////////////////////////////////////////////

vector<int> ans = {0, 0, 1, 0, 2, 0, 2, 0, 4, 0, 96, 0, 1024, 0, 2880, 0, 81024, 0, 770144, 0};   // generated by some brute force
void solve1() {
    int n; cin >> n;
    cout << ans[n];
}

///////////////////////////////////////////////////////////////////////////////////

// JUST ONE MISTAKE, AND YOU ARE HAHAHAHHHHHHHHHHAAAAAAAAAAAAAAA!!!
/* Wo sare problems karo jo lage ki ho jayega but nhi ho pata */

int main()
{
    fastio();
    #ifndef ONLINE_JUDGE
        freopen("io/Error.txt", "w", stderr);
        // freopen("io/Input.txt", "r", stdin);
        // freopen("io/Output.txt", "w", stdout);
    #endif

    isPrime[0] = isPrime[1] = 0;
    f(i, 2, 104) {
        if(isPrime[i]) {
            for(int j = 2*i; j <= 104; j += i) {
                isPrime[j] = 0;
            }
        }
    }

    // int _t; cin >> _t; while(_t--)
    // solve();
    solve1();      // by trick

    return 0;
}